#!/bin/zsh
#Maria Deslis : eternalearth888
#ZSH Prompt

setopt PROMPT_SUBST 

#Autoloads
autoload -U colors && colors
autoload -Uz vcs_info

#Setup VCS_INFO
zstyle ':vcs_info:*' enable git hg
zstyle ':vcs_info:*' formats "%s %r/%S %b %m%u%c"
zstyle ':vcs_info:*' actionformats "%s %r/%S %b %m%u%c"

#From : zirrostig
#Easier Color Usage
local reset white gray green red cyan blue yellow magenta
reset="%{${reset_color}%}"
white="%{$fg[white]%}"
gray="%{$fg[black]%}"
green="%{$fg[green]%}"
blue="%{$fg[blue]%}"
cyan="%{$fg[cyan]%}"
red="%{$fg[red]%}"
yellow="%{$fg[yellow]%}"
magenta="%{$fg[magenta]%}"

#LS Colorization
alias ls="ls --color=auto"

# Check for version control
precmd() {
	vcs_info
}


# PROMPT
PROMPT="${cyan}%n${reset}${white}@${reset}${green}%M${reset}${magenta}${vcs_info_msg_0_}${reset} "

