#!/bin/zsh
#Maria Deslis : eternalearth888
#ZSH Prompt

#autoload -U promptinit
autoload -U colors && colors

#From : zirrostig
#Easier Color Usage
local reset white gray green red cyan blue yellow magenta
reset="%{${reset_color}%}"
white="%{$fg[white]%}"
gray="%{$fg[black]%}"
green="%{$fg[green]%}"
blue="%{$fg[blue]%}"
cyan="%{$fg[cyan]%}"
red="%{$fg[red]%}"
yellow="%{$fg[yellow]%}"
magenta="%{$fg[magenta]%}"

# PROMPT
PROMPT="${cyan}%n${reset}${white}@${reset}${green}%M${reset}${magenta}%~${reset} "

#LS Colorization
alias ls="ls --color=auto"
