#!/bin/zsh
#Maria Deslis : eternalearth888
#ZSH Prompt

#Autoloads
autoload -U colors && colors

#From : zirrostig
#Easier Color Usage
local reset white gray green red cyan blue yellow magenta
reset="%{${reset_color}%}"
white="%{$fg[white]%}"
gray="%{$fg[black]%}"
green="%{$fg[green]%}"
blue="%{$fg[blue]%}"
cyan="%{$fg[cyan]%}"
red="%{$fg[red]%}"
yellow="%{$fg[yellow]%}"
magenta="%{$fg[magenta]%}"

#LS Colorization
alias ls="ls --color=auto"

#Change symbol based on repo type
function prompt_char {
	git branch >/dev/null 2>/dev/null && echo 'G' && return
	hg root >/dev/null 2>/dev/null && echo 'M' && return
	echo 'O'
}

# PROMPT
PROMPT="${cyan}%n${reset}${white}@${reset}${green}%M${reset}${magenta} $(prompt_char)${reset} "
